-- MySQL Script generated by MySQL Workbench
-- mar 17 abr 2018 02:03:26 CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
SHOW WARNINGS;
-- -----------------------------------------------------
-- Schema mantenimientoPC
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mantenimientoPC` ;

-- -----------------------------------------------------
-- Schema mantenimientoPC
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mantenimientoPC` DEFAULT CHARACTER SET latin1 ;
SHOW WARNINGS;
USE `mantenimientoPC` ;

-- -----------------------------------------------------
-- Table `mantenimientoPC`.`Calendario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mantenimientoPC`.`Calendario` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mantenimientoPC`.`Calendario` (
  `idCalendario` INT(11) NOT NULL AUTO_INCREMENT,
  `fecha_mantenimiento` DATE NOT NULL,
  `excepcion` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idCalendario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mantenimientoPC`.`Prioridad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mantenimientoPC`.`Prioridad` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mantenimientoPC`.`Prioridad` (
  `pk_idPrioridad` INT(2) NOT NULL AUTO_INCREMENT,
  `PrioridadNivel` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`pk_idPrioridad`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mantenimientoPC`.`Solicitud`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mantenimientoPC`.`Solicitud` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mantenimientoPC`.`Solicitud` (
  `pk_idSolicitud` INT(3) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  `correo` VARCHAR(150) NULL DEFAULT NULL,
  PRIMARY KEY (`pk_idSolicitud`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mantenimientoPC`.`Sub_TipoMantenimiento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mantenimientoPC`.`Sub_TipoMantenimiento` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mantenimientoPC`.`Sub_TipoMantenimiento` (
  `pk_idSub_TipoMantenimiento` INT(2) NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(70) NOT NULL,
  PRIMARY KEY (`pk_idSub_TipoMantenimiento`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mantenimientoPC`.`TipoMantenimiento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mantenimientoPC`.`TipoMantenimiento` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mantenimientoPC`.`TipoMantenimiento` (
  `pk_idTipoMantenimiento` INT(2) NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(70) NOT NULL,
  `Sub_TipoMantenimiento_pk_idSub_TipoMantenimiento` INT(2) NOT NULL,
  PRIMARY KEY (`pk_idTipoMantenimiento`),
  CONSTRAINT `fk_TipoMantenimiento_Sub_TipoMantenimiento1`
    FOREIGN KEY (`Sub_TipoMantenimiento_pk_idSub_TipoMantenimiento`)
    REFERENCES `mantenimientoPC`.`Sub_TipoMantenimiento` (`pk_idSub_TipoMantenimiento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;
CREATE INDEX `fk_TipoMantenimiento_Sub_TipoMantenimiento1_idx` ON `mantenimientoPC`.`TipoMantenimiento` (`Sub_TipoMantenimiento_pk_idSub_TipoMantenimiento` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mantenimientoPC`.`Unidad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mantenimientoPC`.`Unidad` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mantenimientoPC`.`Unidad` (
  `pk_idUnidad` INT(2) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`pk_idUnidad`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mantenimientoPC`.`OrdenTrabajo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mantenimientoPC`.`OrdenTrabajo` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mantenimientoPC`.`OrdenTrabajo` (
  `pk_idOrdenTrabajo` INT(6) NOT NULL AUTO_INCREMENT,
  `solicitudDescripcion` TEXT NULL DEFAULT NULL,
  `solicitudFecha` DATE NULL DEFAULT NULL,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `clienteEmail` VARCHAR(45) NULL DEFAULT NULL,
  `clienteTelefono` VARCHAR(15) NULL DEFAULT NULL,
  `clienteDomicilio` VARCHAR(45) NULL DEFAULT NULL,
  `Estado` TINYINT(1) NOT NULL,
  `ordenTrabajoAprobadaFecha` DATE NULL DEFAULT NULL,
  `tecnicoDiagnostico` TEXT NULL DEFAULT NULL,
  `posibleFechaEntrega` DATE NULL DEFAULT NULL,
  `TipoMantenimiento_pk_idTipoMantenimiento` INT(2) NOT NULL,
  `Solicitud_pk_idSolicitud` INT(3) NOT NULL,
  `Unidad_pk_idUnidad` INT(2) NOT NULL,
  `Prioridad_pk_idPrioridad` INT(2) NOT NULL,
  PRIMARY KEY (`pk_idOrdenTrabajo`),
  CONSTRAINT `fk_OrdenTrabajo_Prioridad1`
    FOREIGN KEY (`Prioridad_pk_idPrioridad`)
    REFERENCES `mantenimientoPC`.`Prioridad` (`pk_idPrioridad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OrdenTrabajo_Solicitud1`
    FOREIGN KEY (`Solicitud_pk_idSolicitud`)
    REFERENCES `mantenimientoPC`.`Solicitud` (`pk_idSolicitud`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OrdenTrabajo_TipoMantenimiento1`
    FOREIGN KEY (`TipoMantenimiento_pk_idTipoMantenimiento`)
    REFERENCES `mantenimientoPC`.`TipoMantenimiento` (`pk_idTipoMantenimiento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OrdenTrabajo_Unidad1`
    FOREIGN KEY (`Unidad_pk_idUnidad`)
    REFERENCES `mantenimientoPC`.`Unidad` (`pk_idUnidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;
CREATE INDEX `fk_OrdenTrabajo_TipoMantenimiento1_idx` ON `mantenimientoPC`.`OrdenTrabajo` (`TipoMantenimiento_pk_idTipoMantenimiento` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_OrdenTrabajo_Solicitud1_idx` ON `mantenimientoPC`.`OrdenTrabajo` (`Solicitud_pk_idSolicitud` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_OrdenTrabajo_Unidad1_idx` ON `mantenimientoPC`.`OrdenTrabajo` (`Unidad_pk_idUnidad` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_OrdenTrabajo_Prioridad1_idx` ON `mantenimientoPC`.`OrdenTrabajo` (`Prioridad_pk_idPrioridad` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mantenimientoPC`.`Diagnostico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mantenimientoPC`.`Diagnostico` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mantenimientoPC`.`Diagnostico` (
  `pK_idDiagnostico` INT(2) NOT NULL,
  `OrdenTrabajo_pk_idOrdenTrabajo` INT(6) NOT NULL,
  `descripcionGeneral` TEXT NULL,
  PRIMARY KEY (`pK_idDiagnostico`, `OrdenTrabajo_pk_idOrdenTrabajo`),
  CONSTRAINT `fk_Diagnostico_OrdenTrabajo1`
    FOREIGN KEY (`OrdenTrabajo_pk_idOrdenTrabajo`)
    REFERENCES `mantenimientoPC`.`OrdenTrabajo` (`pk_idOrdenTrabajo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;
CREATE INDEX `fk_Diagnostico_OrdenTrabajo1_idx` ON `mantenimientoPC`.`Diagnostico` (`OrdenTrabajo_pk_idOrdenTrabajo` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mantenimientoPC`.`fabricantes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mantenimientoPC`.`fabricantes` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mantenimientoPC`.`fabricantes` (
  `idFabricante` INT(3) NOT NULL,
  `nombre` VARCHAR(60) NOT NULL,
  `descripcion_Fabricante` TEXT NULL DEFAULT NULL,
  `correo_Fabricante` VARCHAR(45) NULL DEFAULT NULL,
  `telefono` VARCHAR(45) NULL DEFAULT NULL,
  `direccion` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`idFabricante`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mantenimientoPC`.`Equipo_detalle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mantenimientoPC`.`Equipo_detalle` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mantenimientoPC`.`Equipo_detalle` (
  `pk_idEquipoDetalle` INT(4) NOT NULL AUTO_INCREMENT,
  `noSerie` VARCHAR(15) NULL,
  `noInventario` VARCHAR(30) NULL DEFAULT NULL,
  `partNumber` VARCHAR(20) NULL DEFAULT NULL,
  `modelo` VARCHAR(45) NULL DEFAULT NULL,
  `hardware_sofware` TINYINT(1) NOT NULL,
  `sofware` VARCHAR(45) NULL DEFAULT NULL,
  `version` VARCHAR(20) NULL DEFAULT NULL,
  `arquitectura3264` TINYINT(1) NULL DEFAULT NULL,
  `licencia` TINYINT(1) NULL DEFAULT NULL,
  `observaciones` TEXT NULL DEFAULT NULL,
  `fabricantes_idFabricante` INT(3) NOT NULL,
  `Equipo_detalle_pk_idEquipoDetalle` INT(4) NOT NULL,
  PRIMARY KEY (`pk_idEquipoDetalle`),
  CONSTRAINT `fk_Equipo_detalle_fabricantes1`
    FOREIGN KEY (`fabricantes_idFabricante`)
    REFERENCES `mantenimientoPC`.`fabricantes` (`idFabricante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Equipo_detalle_Equipo_detalle1`
    FOREIGN KEY (`Equipo_detalle_pk_idEquipoDetalle`)
    REFERENCES `mantenimientoPC`.`Equipo_detalle` (`pk_idEquipoDetalle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;
CREATE INDEX `fk_Equipo_detalle_fabricantes1_idx` ON `mantenimientoPC`.`Equipo_detalle` (`fabricantes_idFabricante` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_Equipo_detalle_Equipo_detalle1_idx` ON `mantenimientoPC`.`Equipo_detalle` (`Equipo_detalle_pk_idEquipoDetalle` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mantenimientoPC`.`Diagnostico_parte`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mantenimientoPC`.`Diagnostico_parte` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mantenimientoPC`.`Diagnostico_parte` (
  `pk_idDianostico_parte` INT(3) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `Diagnostico_pK_idDiagnostico` INT(2) NOT NULL,
  `Diagnostico_OrdenTrabajo_pk_idOrdenTrabajo` INT(6) NOT NULL,
  `Equipo_detalle_pk_idEquipoDetalle` INT(4) NOT NULL,
  PRIMARY KEY (`pk_idDianostico_parte`),
  CONSTRAINT `fk_Dianostico_parte_Diagnostico1`
    FOREIGN KEY (`Diagnostico_pK_idDiagnostico` , `Diagnostico_OrdenTrabajo_pk_idOrdenTrabajo`)
    REFERENCES `mantenimientoPC`.`Diagnostico` (`pK_idDiagnostico` , `OrdenTrabajo_pk_idOrdenTrabajo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Diagnostico_parte_Equipo_detalle1`
    FOREIGN KEY (`Equipo_detalle_pk_idEquipoDetalle`)
    REFERENCES `mantenimientoPC`.`Equipo_detalle` (`pk_idEquipoDetalle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;
CREATE INDEX `fk_Dianostico_parte_Diagnostico1_idx` ON `mantenimientoPC`.`Diagnostico_parte` (`Diagnostico_pK_idDiagnostico` ASC, `Diagnostico_OrdenTrabajo_pk_idOrdenTrabajo` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_Diagnostico_parte_Equipo_detalle1_idx` ON `mantenimientoPC`.`Diagnostico_parte` (`Equipo_detalle_pk_idEquipoDetalle` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mantenimientoPC`.`Pasos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mantenimientoPC`.`Pasos` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mantenimientoPC`.`Pasos` (
  `pk_idPaso` INT(3) NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NOT NULL,
  `observacion` TEXT NULL DEFAULT NULL,
  `duracion_Paso` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`pk_idPaso`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mantenimientoPC`.`Tipo_procedimiento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mantenimientoPC`.`Tipo_procedimiento` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mantenimientoPC`.`Tipo_procedimiento` (
  `pk_idTipo_procedimiento` INT(3) NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NOT NULL,
  `observacion` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`pk_idTipo_procedimiento`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mantenimientoPC`.`Procedimientos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mantenimientoPC`.`Procedimientos` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mantenimientoPC`.`Procedimientos` (
  `nombre_Procedimiento` VARCHAR(60) NULL DEFAULT NULL,
  `Tipo_procedimiento_pk_idTipo_procedimiento` INT(3) NOT NULL,
  `Pasos_pk_idPaso` INT(3) NOT NULL,
  `Diagnostico_parte_pk_idDianostico_parte` INT(3) NOT NULL,
  PRIMARY KEY (`Tipo_procedimiento_pk_idTipo_procedimiento`, `Pasos_pk_idPaso`, `Diagnostico_parte_pk_idDianostico_parte`),
  CONSTRAINT `fk_Procedimientos_Pasos1`
    FOREIGN KEY (`Pasos_pk_idPaso`)
    REFERENCES `mantenimientoPC`.`Pasos` (`pk_idPaso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Procedimientos_Tipo_procedimiento1`
    FOREIGN KEY (`Tipo_procedimiento_pk_idTipo_procedimiento`)
    REFERENCES `mantenimientoPC`.`Tipo_procedimiento` (`pk_idTipo_procedimiento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Procedimientos_Diagnostico_parte1`
    FOREIGN KEY (`Diagnostico_parte_pk_idDianostico_parte`)
    REFERENCES `mantenimientoPC`.`Diagnostico_parte` (`pk_idDianostico_parte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;
CREATE INDEX `fk_Procedimientos_Pasos1_idx` ON `mantenimientoPC`.`Procedimientos` (`Pasos_pk_idPaso` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_Procedimientos_Diagnostico_parte1_idx` ON `mantenimientoPC`.`Procedimientos` (`Diagnostico_parte_pk_idDianostico_parte` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mantenimientoPC`.`Estado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mantenimientoPC`.`Estado` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mantenimientoPC`.`Estado` (
  `pk_idEstado` INT(2) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  `Procedimientos_Tipo_procedimiento_pk_idTipo_procedimiento` INT(3) NOT NULL,
  `Procedimientos_Pasos_pk_idPaso` INT(3) NOT NULL,
  `Procedimientos_Diagnostico_parte_pk_idDianostico_parte` INT(3) NOT NULL,
  PRIMARY KEY (`pk_idEstado`, `Procedimientos_Tipo_procedimiento_pk_idTipo_procedimiento`, `Procedimientos_Pasos_pk_idPaso`, `Procedimientos_Diagnostico_parte_pk_idDianostico_parte`),
  CONSTRAINT `fk_Estado_Procedimientos1`
    FOREIGN KEY (`Procedimientos_Tipo_procedimiento_pk_idTipo_procedimiento` , `Procedimientos_Pasos_pk_idPaso` , `Procedimientos_Diagnostico_parte_pk_idDianostico_parte`)
    REFERENCES `mantenimientoPC`.`Procedimientos` (`Tipo_procedimiento_pk_idTipo_procedimiento` , `Pasos_pk_idPaso` , `Diagnostico_parte_pk_idDianostico_parte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;
CREATE INDEX `fk_Estado_Procedimientos1_idx` ON `mantenimientoPC`.`Estado` (`Procedimientos_Tipo_procedimiento_pk_idTipo_procedimiento` ASC, `Procedimientos_Pasos_pk_idPaso` ASC, `Procedimientos_Diagnostico_parte_pk_idDianostico_parte` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mantenimientoPC`.`Personal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mantenimientoPC`.`Personal` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mantenimientoPC`.`Personal` (
  `pk_idPersonal` INT(3) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `dui` VARCHAR(45) NOT NULL,
  `nit` VARCHAR(45) NOT NULL,
  `estado` TINYINT(1) NOT NULL,
  `empleadoEstudiante` TINYINT(1) NOT NULL,
  `due` VARCHAR(45) NULL DEFAULT NULL,
  `domicilio` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`pk_idPersonal`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mantenimientoPC`.`Estado_detalle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mantenimientoPC`.`Estado_detalle` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mantenimientoPC`.`Estado_detalle` (
  `Personal_pk_idPersonal` INT(3) NOT NULL,
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  `Estado_pk_idEstado` INT(2) NOT NULL,
  `Estado_Estado_pk_idEstado` INT(2) NOT NULL,
  `Estado_Procedimientos_Tipo_procedimiento_pk_idTipo_procedimiento` INT(3) NOT NULL,
  `Estado_Procedimientos_Pasos_pk_idPaso` INT(3) NOT NULL,
  `Estado_Procedimientos_Diagnostico_parte_pk_idDianostico_parte` INT(3) NOT NULL,
  PRIMARY KEY (`Personal_pk_idPersonal`, `Estado_pk_idEstado`, `Estado_Estado_pk_idEstado`, `Estado_Procedimientos_Tipo_procedimiento_pk_idTipo_procedimiento`, `Estado_Procedimientos_Pasos_pk_idPaso`, `Estado_Procedimientos_Diagnostico_parte_pk_idDianostico_parte`),
  CONSTRAINT `fk_Estado_detalle_Personal1`
    FOREIGN KEY (`Personal_pk_idPersonal`)
    REFERENCES `mantenimientoPC`.`Personal` (`pk_idPersonal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Estado_detalle_Estado1`
    FOREIGN KEY (`Estado_pk_idEstado` , `Estado_Procedimientos_Tipo_procedimiento_pk_idTipo_procedimiento` , `Estado_Procedimientos_Pasos_pk_idPaso` , `Estado_Procedimientos_Diagnostico_parte_pk_idDianostico_parte`)
    REFERENCES `mantenimientoPC`.`Estado` (`pk_idEstado` , `Procedimientos_Tipo_procedimiento_pk_idTipo_procedimiento` , `Procedimientos_Pasos_pk_idPaso` , `Procedimientos_Diagnostico_parte_pk_idDianostico_parte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;
CREATE INDEX `fk_Estado_detalle_Estado1_idx` ON `mantenimientoPC`.`Estado_detalle` (`Estado_pk_idEstado` ASC, `Estado_Estado_pk_idEstado` ASC, `Estado_Procedimientos_Tipo_procedimiento_pk_idTipo_procedimiento` ASC, `Estado_Procedimientos_Pasos_pk_idPaso` ASC, `Estado_Procedimientos_Diagnostico_parte_pk_idDianostico_parte` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mantenimientoPC`.`Rol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mantenimientoPC`.`Rol` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mantenimientoPC`.`Rol` (
  `pk_idRol` INT(3) NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`pk_idRol`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mantenimientoPC`.`HistorialTrabajo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mantenimientoPC`.`HistorialTrabajo` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mantenimientoPC`.`HistorialTrabajo` (
  `pk_idHistorialTrabajo` INT(6) NOT NULL AUTO_INCREMENT,
  `fechaInicio` DATE NOT NULL,
  `fechaFin` DATE NULL DEFAULT NULL,
  `Rol_pk_idRol` INT(3) NOT NULL,
  `Personal_pk_idPersonal` INT(3) NOT NULL,
  PRIMARY KEY (`pk_idHistorialTrabajo`),
  CONSTRAINT `fk_HistorialTrabajo_Personal1`
    FOREIGN KEY (`Personal_pk_idPersonal`)
    REFERENCES `mantenimientoPC`.`Personal` (`pk_idPersonal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_HistorialTrabajo_Rol`
    FOREIGN KEY (`Rol_pk_idRol`)
    REFERENCES `mantenimientoPC`.`Rol` (`pk_idRol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;
CREATE INDEX `fk_HistorialTrabajo_Rol_idx` ON `mantenimientoPC`.`HistorialTrabajo` (`Rol_pk_idRol` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_HistorialTrabajo_Personal1_idx` ON `mantenimientoPC`.`HistorialTrabajo` (`Personal_pk_idPersonal` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mantenimientoPC`.`Mantenimiento_detalle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mantenimientoPC`.`Mantenimiento_detalle` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mantenimientoPC`.`Mantenimiento_detalle` (
  `pk_idMantenimiento_detallecol` INT(4) NOT NULL,
  `fecha` DATE NOT NULL,
  `observaciones` TEXT NULL DEFAULT NULL,
  `OrdenTrabajo_pk_idOrdenTrabajo` INT(6) NOT NULL,
  `Estado_pk_idEstado` INT(2) NOT NULL,
  `Estado_Procedimientos_Tipo_procedimiento_pk_idTipo_procedimiento` INT(3) NOT NULL,
  `Estado_Procedimientos_Pasos_pk_idPaso` INT(3) NOT NULL,
  `Estado_Procedimientos_Diagnostico_parte_pk_idDianostico_parte` INT(3) NOT NULL,
  `Equipo_detalle_pk_idEquipoDetalle` INT(4) NOT NULL,
  PRIMARY KEY (`pk_idMantenimiento_detallecol`, `OrdenTrabajo_pk_idOrdenTrabajo`, `Estado_pk_idEstado`, `Estado_Procedimientos_Tipo_procedimiento_pk_idTipo_procedimiento`, `Estado_Procedimientos_Pasos_pk_idPaso`, `Estado_Procedimientos_Diagnostico_parte_pk_idDianostico_parte`),
  CONSTRAINT `fk_Mantenimiento_detalle_OrdenTrabajo1`
    FOREIGN KEY (`OrdenTrabajo_pk_idOrdenTrabajo`)
    REFERENCES `mantenimientoPC`.`OrdenTrabajo` (`pk_idOrdenTrabajo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Mantenimiento_detalle_Estado1`
    FOREIGN KEY (`Estado_pk_idEstado` , `Estado_Procedimientos_Tipo_procedimiento_pk_idTipo_procedimiento` , `Estado_Procedimientos_Pasos_pk_idPaso` , `Estado_Procedimientos_Diagnostico_parte_pk_idDianostico_parte`)
    REFERENCES `mantenimientoPC`.`Estado` (`pk_idEstado` , `Procedimientos_Tipo_procedimiento_pk_idTipo_procedimiento` , `Procedimientos_Pasos_pk_idPaso` , `Procedimientos_Diagnostico_parte_pk_idDianostico_parte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Mantenimiento_detalle_Equipo_detalle1`
    FOREIGN KEY (`Equipo_detalle_pk_idEquipoDetalle`)
    REFERENCES `mantenimientoPC`.`Equipo_detalle` (`pk_idEquipoDetalle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;
CREATE INDEX `fk_Mantenimiento_detalle_OrdenTrabajo1_idx` ON `mantenimientoPC`.`Mantenimiento_detalle` (`OrdenTrabajo_pk_idOrdenTrabajo` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_Mantenimiento_detalle_Estado1_idx` ON `mantenimientoPC`.`Mantenimiento_detalle` (`Estado_pk_idEstado` ASC, `Estado_Procedimientos_Tipo_procedimiento_pk_idTipo_procedimiento` ASC, `Estado_Procedimientos_Pasos_pk_idPaso` ASC, `Estado_Procedimientos_Diagnostico_parte_pk_idDianostico_parte` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_Mantenimiento_detalle_Equipo_detalle1_idx` ON `mantenimientoPC`.`Mantenimiento_detalle` (`Equipo_detalle_pk_idEquipoDetalle` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mantenimientoPC`.`Telefono`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mantenimientoPC`.`Telefono` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mantenimientoPC`.`Telefono` (
  `pk_idTelefono` INT(5) NOT NULL AUTO_INCREMENT,
  `Telefono` VARCHAR(45) NOT NULL,
  `Personal_pk_idPersonal` INT(3) NOT NULL,
  PRIMARY KEY (`pk_idTelefono`),
  CONSTRAINT `fk_Telefono_Personal1`
    FOREIGN KEY (`Personal_pk_idPersonal`)
    REFERENCES `mantenimientoPC`.`Personal` (`pk_idPersonal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;
CREATE INDEX `fk_Telefono_Personal1_idx` ON `mantenimientoPC`.`Telefono` (`Personal_pk_idPersonal` ASC);

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
